from overStat import *
import pprint

battle_tag = 'GloverDude#1471'

ow = OverStatAPI('key')

""" --- Request Stats --- """
stats = ow.get_stats(battle_tag)
print(pprint.pformat(stats))
"""
{'_request': {'api_ver': 1, 'route': '/api/v2/u/GloverDude-1471/stats/general'},
 'battletag': 'GloverDude-1471',
 'game_stats': {'cards': 134.0,
                'damage_done': 1846927.0,
                'damage_done_most_in_game': 22312.0,
                'deaths': 2460.0,
                'defensive_assists': 467.0,
                'defensive_assists_most_in_game': 28.0,
                'eliminations': 4317.0,
                'eliminations_most_in_game': 46.0,
                'environmental_deaths': 55.0,
                'environmental_kills': 33.0,
                'final_blows': 2483.0,
                'final_blows_most_in_game': 25.0,
                'games_played': 354.0,
                'games_won': 176.0,
                'healing_done': 446029.0,
                'healing_done_most_in_game': 9753.0,
                'kpd': 1.75,
                'medals': 869.0,
                'medals_bronze': 235.0,
                'medals_gold': 357.0,
                'medals_silver': 277.0,
                'melee_final_blows': 1.0,
                'melee_final_blows_most_in_game': 1.0,
                'multikill_best': 5.0,
                'multikills': 25.0,
                'objective_kills': 1525.0,
                'objective_kills_most_in_game': 23.0,
                'objective_time': '02:57:59',
                'objective_time_most_in_game': '04:39',
                'offensive_assists': 104.0,
                'offensive_assists_most_in_game': 16.0,
                'recon_assists': 14.0,
                'solo_kills': 1018.0,
                'solo_kills_most_in_game': 25.0,
                'teleporter_pads_destroyed': 2.0,
                'time_played': '47 hours',
                'time_spent_on_fire': '05:47:25',
                'time_spent_on_fire_most_in_game': '09:49'},
 'overall_stats': {'comprank': 45,
                   'games': 354,
                   'level': 61,
                   'losses': 178,
                   'rank': None,
                   'win_rate': 49,
                   'wins': 176},
 'region': 'us'}
"""

""" --- Request Top 5 Heroes Stats --- """
stats = ow.get_hero(battle_tag,'1')
print(pprint.pformat(stats))
"""
{'_request': {'api_ver': 1, 'route': '/api/v1/u/GloverDude-1471/heroes/1'},
 'battletag': 'GloverDude-1471',
 'region': 'us',
 'stats': [{'name': 'hero-specific stats',
            'stats': [{'name': 'average enemies hooked', 'value': 15.0},
                      {'name': 'average healing done', 'value': 3199.0},
                      {'name': 'average self healing', 'value': 0.0},
                      {'name': 'average whole hog kills', 'value': 3.0},
                      {'name': 'best enemies hooked', 'value': 30.0},
                      {'name': 'best healing done', 'value': 6378.0},
                      {'name': 'best hook accuracy in game', 'value': '100%'},
                      {'name': 'best self healing', 'value': 6378.0},
                      {'name': 'best whole hog kills', 'value': 11.0},
                      {'name': 'one life healing done', 'value': 3174.0},
                      {'name': 'total enemies hooked', 'value': 889.0},
                      {'name': 'total healing done', 'value': 185180.0},
                      {'name': 'total hook accuracy', 'value': '51%'},
                      {'name': 'total hooks attempted', 'value': 1738.0},
                      {'name': 'total self healing', 'value': 185180.0},
                      {'name': 'total whole hog kills', 'value': 177.0}]},
           {'name': 'overall',
            'stats': [{'name': 'final blows', 'value': 562.0},
                      {'name': 'eliminations', 'value': 942.0},
                      {'name': 'deaths', 'value': 393.0},
                      {'name': 'damage done', 'value': 378775.0},
                      {'name': 'score', 'value': 0.0},
                      {'name': 'melee kills', 'value': 0.0},
                      {'name': 'time played', 'value': '8 hours'},
                      {'name': 'time on fire', 'value': '3 hours'},
                      {'name': 'objective kills', 'value': 335.0},
                      {'name': 'objective time', 'value': '47 minutes'},
                      {'name': 'accuracy', 'value': '32%'},
                      {'name': 'medals earned', 'value': 211.0},
                      {'name': 'cards earned', 'value': 43.0}]},
           {'name': 'averages per game',
            'stats': [{'name': 'final blows', 'value': 9.7},
                      {'name': 'eliminations', 'value': 16.27},
                      {'name': 'deaths', 'value': 6.78},
                      {'name': 'damage done', 'value': 6543.0},
                      {'name': 'objective kills', 'value': 5.78},
                      {'name': 'objective time', 'value': '49.09 seconds'}]},
           {'name': 'best in one game',
            'stats': [{'name': 'final blows', 'value': 23.0},
                      {'name': 'eliminations', 'value': 33.0},
                      {'name': 'killstreak', 'value': 0.0},
                      {'name': 'damage done', 'value': 13139.0},
                      {'name': 'objective kills', 'value': 19.0},
                      {'name': 'objective time', 'value': 200.0},
                      {'name': 'accuracy', 'value': '-'}]},
           {'name': 'best in one life',
            'stats': [{'name': 'eliminations', 'value': 24.0},
                      {'name': 'damage done', 'value': 7465.0},
                      {'name': 'score', 'value': 0.0}]}]}
"""
